name = "reinformtech-admin"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
GMAIL_EMAIL = "reinformtech@gmail.com"
GMAIL_APP_PASSWORD = "znkusrfskatlsubs"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
